version: '3.9'
services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./:/app
    restart: always
    tty: true
    stdin_open: true
    command: "bash entrypoint.sh"
